services:
  db:
    image: dvp-srv-gitlab.campus12avenue.fr:5050/tp-devops-2526/s04/flowfield/postgres:16
    environment:
      POSTGRES_DB: flowfield
      POSTGRES_USER: flowfield
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowfield"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: dvp-srv-gitlab.campus12avenue.fr:5050/tp-devops-2526/s04/flowfield/backend:${IMAGE_TAG:-latest}
    environment:
      - DATABASE_URL=postgresql://flowfield:${DB_PASSWORD}@db:5432/flowfield
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: dvp-srv-gitlab.campus12avenue.fr:5050/tp-devops-2526/s04/flowfield/frontend:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  export:
    image: dvp-srv-gitlab.campus12avenue.fr:5050/tp-devops-2526/s04/flowfield/export:${IMAGE_TAG:-latest}
    restart: unless-stopped

volumes:
  postgres_data:
